telegram:
  bot:
#    token:
    receiver-type: pool # Тип прослушивания телеги: через вебхук (webhook) или через пул (poll)
#  webhook: # Если webhook, то нужно задать эти проперти
#    url:
#    port:
    menu:
      items-per-page: 5
    admins: # ID телеграма-аккаунта
      - 1327325938 # Рома
      - 803555618 # Настя

external-links:
  backend-url: http://localhost:8080/
  vk-group: https://vk.com/vega_bot
  telegram-vega-chat: https://t.me/vegajn
  telegram-suggestion-chat: https://t.me/+Xu730w6PuTliMjBi
  spo-bot-url: https://t.me/VegaSPO_bot
  service-contact: https://t.me/kuanpa

cache.duration: # Duration of caches.
  session: 10m
  backend-data: 1h

server.port: 8081

# TODO Костыль, убрать. См TODO.md

spring:
  main:
    allow-circular-references: true
