spring:
  datasource:
    url: jdbc:h2:file:./vega-db
    username: vega
    password:
    platform: h2
    driver-class-name: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  jpa.hibernate.ddl-auto: update
